### PR TITLE
Simplify project Makefiles

### PR DESCRIPTION
**Pull request by bbaltz505**
stripped down project makefile. just list your needed library paths and the top makefile will figure out the include paths and source files needed

### CODE REVIEW

**Comment by bbaltz505** [comment]
@calvinatintel @intel-larry

**Comment by calvinatintel** [comment]
Can you provide the steps to compile a sketch? I've been having difficulties.

**Comment by bbaltz505** [comment]
1. cd examples/Blink
2. make convert-sketch SKETCH=$(pwd)/Blink.ino
3. *edit your Makefile if needed*
4. make compile

**Comment by calvinatintel** [comment]
Looks good to me!

**Comment by eriknyquist** [comment]
Looks good. On an unrelated note, could you add an example sketch that requires an extra library, just so there's an example of what should go in LIBDIRS?

**Comment by bbaltz505** [comment]
Good idea. Let me pull one of our corelibs examples.

**Comment by eriknyquist** [comment]
Also, I as thinking it might make more sense to include the examples as already-converted .cpp files. Otherwise, we're kind of suggesting that writing a "sketch" as a .ino file and the running 'make convert-sketch' is a normal workflow. Really, it's just a bonus for people who want to migrate a sketch over to CODK, and continue developing it as C++.

**Comment by bbaltz505** [comment]
The ASCIITable example is provided as a C++ project (I just renamed the .ino to .cpp and added the include for Arduino.h). Converted C++ sketches are pretty ugly to read but I can try manually converting a small multi-file example sketch.

**Comment by eriknyquist** [comment]
I guess it was just Blink.ino. I've added it in a new PR.

**Comment by bbaltz505** [comment]
@eriknyquist added a C++ version (manually converted) of CurieEEPROM example sketch

**Comment by eriknyquist** [comment]
@bbaltz505 looks good. The only ugliness I saw was all the #defines for line numbers, do you think that's something we could strip out? or does arduino-builder leave other things (we don't need) in there too?

**Comment by bbaltz505** [comment]
I need to rebase this PR. @eriknyquist I think they user may find the line #s helpful as it ties that portion of the C++ file to the sketch file (in a multi-file sketch).

**Comment by eriknyquist** [comment]
Oh, OK yeah fair enough.

**Pull request closed without merging**
